version: 0.2

env:
  variables:
    PATH: "/opt/apache-tomcat-11.0.9/bin:$PATH"

phases:
  install:
    runtime-versions:
      java: corretto17   # or openjdk17, depending on CodeBuild image
      maven: 3.8
    commands:
      - echo "Installing dependencies..."
      - mvn -version
      - java -version

  pre_build:
    commands:
      - echo "Cloning repository..."
      - git clone -b main https://github.com/s43861999/first-project.git
      - cd first-project

  build:
    commands:
      - echo "Running Maven build..."
      - mvn clean install

  post_build:
    commands:
      - echo "Copying WAR file to Tomcat server..."
      - ls -l target/
      - pwd
      - scp -o StrictHostKeyChecking=no target/webapp.war ubuntu@ec2-54-88-176-248.compute-1.amazonaws.com:/opt/apache-tomcat-11.0.9/webapps

artifacts:
  files:
    - target/webapp.war
